version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adminadmin
      MYSQL_DATABASE: unjumble_app
      MYSQL_USER: root
      MYSQL_PASSWORD: adminadmin
    ports:
      - "3306:3306"

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_ENV: production
      DATABASE_URL: mysql+pymysql://root:adminadmin@db/unjumble_app
    volumes:
      - upload_volume:/opt/uploads/assets/

volumes:
  db_data: {}
  upload_volume: {}
